### ISSUE TITLE
Returning to old target route when relogging in.

### ISSUE THREAD

**Issue by KennethicEnergy** [NirmalScaria/firebase-nextjs#10]
it adds a `?target=/route-name` when logging out then redirects the user to target url when logging in.

**Comment by KennethicEnergy** [comment]
+ even if different user will be logged in, if there's the `?target=/route-name`, it will be redirected to that page.

**Comment by NirmalScaria** [comment]
@KennethicEnergy  This has been fixed in the latest version. You can provide an optional parameter "persistRoute" to the log out button. If true, the user will log back in to the same page. By default, it has been set to false.
