### ISSUE TITLE
Correct "npx firebase-nextjs getenev" command in README.md 

### ISSUE THREAD

**Issue by bpmcdonell** [NirmalScaria/firebase-nextjs#17]
Fantastic work on this project, easily the simplest Next.JS auth solution I've come across so far. Took me all of 15 minutes to get it all set up.

Super small issue, thought I should bring it to your attention though. 

In your README.md and the [website](https://firebase-nextjs.scaria.dev/production) for this repo has the incorrect command listed for getting the env. It is currently showing `npx firebase-nextjs getenev` when the correct (working) command is `npx firebase-nextjs getenv`. 

Keep up the great work!

**Comment by NirmalScaria** [comment]
Hey, Thank you for pointing out the issue. It was a stupid mistake from me.

Fixed it. Thanks. :)
